Obligatorio/urls.py
from django.urls import re_path as url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^biblio/', include('biblio.urls'))
]

biblio/urls.py
from django.urls import re_path as url, include
from biblio import views

import biblio.controllers.libros as librocontroller
import biblio.controllers.socios as sociocontroller
import biblio.controllers.copias as copiacontroller
import biblio.controllers.prestamos as prestamocontroller


app_name = 'biblio'

urlpatterns = [
    # Auth
    url(r'^auth/', include([
        url(r'^login$', views.LoginController.as_view(), name='login'),
        url(r'^logout$', views.my_logout, name='logout')
    ])),

    # Index
    url(r'^$', views.index, name='index'),

    # ABM Prestamo
    url(r'^prestamo$', prestamocontroller.get_prestamo, name='prestamos'),
    url(r'^prestamo/(?P<id_prestamo>\d+)$', prestamocontroller.get_prestamo),
    url(r'^prestamo/(?P<id_socio>\w+)/(?P<isbn>\w+)$', prestamocontroller.create_prestamo),

    # Prestamos por fecha
    url(r'^prestamo_fecha$', prestamocontroller.prestamo_por_fecha, name='prestamos_por_fecha'),
    url(r'^prestamo_fecha/(?P<fecha>\d{4}-\d{2}-\d{2})$', prestamocontroller.prestamo_por_fecha),

    # ABM Devolucion
    url(r'^devolucion/(?P<id_socio>\w+)/(?P<nro_inventario>\d+)$', prestamocontroller.create_devolucion),

    # ABM Socio
    url(r'^socio$', sociocontroller.get_socio, name='socios'),
    url(r'^socio/(?P<id_socio>\d+)$', sociocontroller.get_socio),
    url(r'^socio/create$', sociocontroller.create_socio),
    url(r'^socio/(?P<sid>\d+)/edit$', sociocontroller.edit_socio),
    url(r'^socio/(?P<sid>\d+)/delete$', sociocontroller.delete_socio),

    # ABM CopiaLibro
    url(r'^copia$', copiacontroller.get_copia, name='copias'),
    url(r'^copia/(?P<inventario>\d+)$', copiacontroller.get_copia),
    url(r'^copia/create$', copiacontroller.create_copia),
    url(r'^copia/(?P<inventario>\d+)/delete$', copiacontroller.delete_copia),

    # ABM Libro
    url(r'^libro$', librocontroller.get_libro, name='libros'),
    url(r'^libro/(?P<isbn>\d{10})$', librocontroller.get_libro),
    url(r'^libro/create$', librocontroller.create_libro),
    url(r'^libro/(?P<lid>\d+)/edit$', librocontroller.edit_libro),
    url(r'^libro/(?P<lid>\d+)/delete$', librocontroller.delete_libro),

    # Lista de morosos
    url(r'^morosos$', sociocontroller.get_moroso, name='morosos'),

    # Morosos por fecha
    url(r'^morosos_fecha$', sociocontroller.moroso_por_fecha, name='morosos_por_fecha'),
    url(r'^morosos_fecha/(?P<fecha>\d{4}-\d{2}-\d{2})$', sociocontroller.moroso_por_fecha)
]

biblio/models.py
from django.db import models


# Create your models here.
class Libro(models.Model):
    isbn = models.CharField(max_length=15, unique=True)
    titulo = models.CharField(max_length=150)
    autor = models.CharField(max_length=150)
    fecha_ingreso = models.DateField('fecha de ingreso', auto_now=True)

    codigo = models.CharField(max_length=50, null=True, default=None)

    def __str__(self):
        return '[{0}] {1} ({2})'.format(self.isbn, self.titulo, self.autor)


class CopiaLibro(models.Model):
    num_inventario = models.IntegerField(primary_key=True)
    estado = models.CharField(max_length=10, choices=[('p', 'prestado'), ('d', 'disponible')])

    # Claves foraneas
    isbn = models.ForeignKey(Libro, on_delete=models.CASCADE)

    def __str__(self):
        return '[{0}] {1} ({2})'.format(self.num_inventario, self.estado_string().capitalize(), self.isbn)

    def estado_string(self):
        if self.estado == 'p':
            return 'prestado'

        elif self.estado == 'd':
            return 'disponible'


class Socio(models.Model):
    documento = models.CharField(max_length=8, unique=True)
    nombre_completo = models.CharField(max_length=200)
    email = models.CharField(max_length=200, unique=True)
    fecha_nacimiento = models.DateField('fecha de nacimiento')
    estado = models.CharField(max_length=6, choices=[('m', 'moroso'), ('n', 'normal')])

    def __str__(self):
        return '[{0}] {1}'.format(self.documento, self.nombre_completo)

    def estado_string(self):
        if self.estado == 'm':
            return 'moroso'

        elif self.estado == 'n':
            return 'normal'


class Prestamo(models.Model):
    fecha_comienzo = models.DateField('fecha de comienzo')
    fecha_fin = models.DateField('fecha de fin', null=True)
    estado = models.CharField(max_length=9, choices=[('p', 'pendiente'), ('t', 'terminado')])

    # Claves foraneas
    copia_libro_id = models.ForeignKey(CopiaLibro, on_delete=models.CASCADE)
    socio_id = models.ForeignKey(Socio, on_delete=models.CASCADE)

    def __str__(self):
        return '{0} - {1}'.format(self.copia_libro_id.isbn, self.estado_string().capitalize())

    def estado_string(self):
        if self.estado == 'p':
            return 'pendiente'

        elif self.estado == 't':
            return 'terminado'

biblio/controllers/copias.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_http_methods

from biblio.models import CopiaLibro, Libro, Socio


# ABM CopiaLibro
@require_http_methods(["GET"])
def get_copia(req, inventario=None):
    if inventario:
        cop = get_object_or_404(CopiaLibro, pk=inventario)

        json = {
            'error': False,
            'copia': {
                'num_inventario': cop.num_inventario,
                'estado': cop.estado_string().capitalize(),
                'isbn': {
                    'isbn': cop.isbn.isbn,
                    'fecha_ingreso': cop.isbn.fecha_ingreso,
                    'titulo': cop.isbn.titulo,
                    'autor': cop.isbn.autor
                }
            }
        }

        if cop.estado == 'p':
            prestamo = cop.prestamo_set.filter(copia_libro_id=cop, estado='p').get()
            json['socio'] = {
                'documento': prestamo.socio_id.documento,
                'nombre_completo': prestamo.socio_id.nombre_completo,
                'email': prestamo.socio_id.email,
                'fecha_nacimiento': prestamo.socio_id.fecha_nacimiento,
                'estado': prestamo.socio_id.estado
            }

        return JsonResponse(json)

    else:
        copias = CopiaLibro.objects.all()

        return render(req, 'copias/index.html', {
            'copias': copias,
            'libros': Libro.objects.all()
        })


@require_http_methods(["POST"])
def create_copia(req):
    isbn = req.POST['isbn']
    estado = 'd'
    cant = req.POST['cantidad']

    if isbn == '' or cant == '':
        return JsonResponse({
            'error': True,
            'msg': 'Debes completar todos los campos!'
        })

    try:
        lib = get_object_or_404(Libro, isbn=isbn)

        for _ in range(int(cant)):
            clib = CopiaLibro()
            clib.isbn = lib
            clib.estado = estado
            clib.save()

        return JsonResponse({
            'error': False,
            'msg': 'Copias registradas!'
        })

    except Exception as e:
        return JsonResponse({
            'error': True,
            'msg': 'Error: {}'.format(e)
        })


@require_http_methods(["POST"])
def delete_copia(req, inventario):
    cop = get_object_or_404(CopiaLibro, pk=inventario)

    cop.delete()

    return JsonResponse({
        'error': False,
        'msg': 'Copia eliminada!'
    })

biblio/controllers/libros.py
import re

from django.db import IntegrityError
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views.decorators.http import require_http_methods

from biblio.models import CopiaLibro, Libro


# ABM Libro
@require_http_methods(["GET"])
def get_libro(req, isbn=None):
    if isbn:
        lbr = get_object_or_404(Libro, isbn=isbn)
        cop = CopiaLibro.objects.filter(isbn=lbr)

        copias = []
        for c in cop:
            copias.append({
                'nro_inventario': c.num_inventario,
                'estado': c.estado_string().capitalize()
            })

        return JsonResponse({
            'error': False,
            'libro': {
                'id': lbr.id,
                'codigo': lbr.codigo,
                'isbn': lbr.isbn,
                'titulo': lbr.titulo,
                'autor': lbr.autor,
                'fecha_ingreso': lbr.fecha_ingreso,
                'copias': copias
            }
        })

    else:
        libros = Libro.objects.all()

        if req.headers.get('x-requested-with') == 'XMLHttpRequest':
            tmp_list = []
            for l in libros:
                tmp_list.append({
                    'id': l.id,
                    'codigo': l.codigo,
                    'isbn': l.isbn,
                    'titulo': l.titulo,
                    'autor': l.autor,
                    'fecha_ingreso': l.fecha_ingreso
                })

            return JsonResponse({'libros': tmp_list})

        else:
            return render(req, 'libros/index.html', {
                'libros': libros
            })


@require_http_methods(["POST"])
def create_libro(req):
    code = req.POST['code']
    isbn = req.POST['isbn']
    title = req.POST['title']
    author = req.POST['author']

    if code == '' or isbn == '' or title == '' or author == '':
        return JsonResponse({
            'error': True,
            'msg': 'Debes completar todos los campos!'
        })

    patt_isbn = re.compile('^\d{10}$')

    if not patt_isbn.match(isbn):
        return JsonResponse({
            'error': True,
            'msg': 'El ISBN no cumple con el formato. El dato debe ser un numero de 10 digitos'
        })

    try:
        lib = Libro()
        lib.codigo = code
        lib.isbn = isbn
        lib.titulo = title
        lib.autor = author
        lib.fecha_ingreso = timezone.now()
        lib.save()

        return JsonResponse({
            'error': False,
            'msg': 'Libro registrado!'
        })

    except IntegrityError as e:
        return JsonResponse({
            'error': True,
            'msg': 'Ya existe un libro con el ISBN ingresado: {}'.format(e)
        })


@require_http_methods(["POST"])
def edit_libro(req, lid):
    code = req.POST['code']
    isbn = req.POST['isbn']
    title = req.POST['title']
    author = req.POST['author']

    if code == '' or isbn == '' or title == '' or author == '':
        return JsonResponse({
            'error': True,
            'msg': 'Debes completar todos los campos!'
        })

    patt_isbn = re.compile('^\d{10}$')

    if not patt_isbn.match(isbn):
        return JsonResponse({
            'error': True,
            'msg': 'El ISBN no cumple con el formato. El dato debe ser un numero de 10 digitos'
        })

    lbr = get_object_or_404(Libro, pk=lid)

    lbr.codigo = code
    lbr.isbn = isbn
    lbr.titulo = title
    lbr.autor = author
    lbr.save()

    return JsonResponse({
        'error': False,
        'msg': 'Libro editado!'
    })


@require_http_methods(["POST"])
def delete_libro(req, lid):
    lbr = get_object_or_404(Libro, pk=lid)

    lbr.delete()

    return JsonResponse({
        'error': False,
        'msg': 'Libro eliminado!'
    })

biblio/controllers/prestamos.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views.decorators.http import require_http_methods

from biblio.models import Prestamo, Socio, Libro, CopiaLibro


# ABM Prestamo
@require_http_methods(["GET"])
def get_prestamo(req, id_prestamo=None):
    if id_prestamo:
        pr = get_object_or_404(Prestamo, pk=id_prestamo)

        return JsonResponse({
            'error': False,
            'prestamo': {
                'fecha_comienzo': pr.fecha_comienzo,
                'fecha_fin': pr.fecha_fin,
                'estado': pr.estado_string().capitalize(),
                'copia_libro_id': {
                    'num_inventario': pr.copia_libro_id.num_inventario,
                    'estado': pr.copia_libro_id.estado_string().capitalize(),
                    'isbn': {
                        'isbn': pr.copia_libro_id.isbn.isbn,
                        'titulo': pr.copia_libro_id.isbn.titulo,
                        'autor': pr.copia_libro_id.isbn.autor,
                        'fecha_ingreso': pr.copia_libro_id.isbn.fecha_ingreso
                    }
                },
                'socio_id': {
                    'documento': pr.socio_id.documento,
                    'nombre_completo': pr.socio_id.nombre_completo,
                    'email': pr.socio_id.email,
                    'fecha_nacimiento': pr.socio_id.fecha_nacimiento,
                    'estado': pr.socio_id.estado
                }
            }
        })

    else:
        prstms = Prestamo.objects.all()

        return render(req, 'prestamos/index.html', {
            'prestamos': prstms
        })


@require_http_methods(['POST'])
def create_prestamo(req, id_socio=None, isbn=None):
    if id_socio and isbn:
        try:
            soc = get_object_or_404(Socio, id=id_socio)
            if soc.estado != 'n':
                return JsonResponse({
                    'error': True,
                    'msg': 'El socio seleccionado es moroso y no se pueden realizar prestamos a su nombre!'
                })

            lib = Libro.objects.filter(isbn=isbn).first()
            if not lib:
                return JsonResponse({
                    'error': True,
                    'msg': 'No existe un libro con ISBN {}'.format(isbn)
                })

            cop = CopiaLibro.objects.filter(isbn=lib, estado='d').first()
            if not cop:
                return JsonResponse({
                    'error': True,
                    'msg': 'No existe una copia del libro [{0}] {1} ({2}) disponible.'.format(lib.isbn,
                                                                                              lib.titulo, lib.autor)
                })

            cop.estado = 'p'
            cop.save()

            pr = Prestamo()
            pr.fecha_comienzo = timezone.now()
            pr.estado = 'p'
            pr.copia_libro_id = cop
            pr.socio_id = soc

            pr.save()

            return JsonResponse({
                'error': False,
                'msg': 'Préstamo registrado correctamente.'
            })

        except Exception as e:
            return JsonResponse({
                'error': True,
                'msg': 'Error: {}'.format(e)
            })

    else:
        return JsonResponse({
            'error': True,
            'msg': 'Debes completar todos los campos!'
        })


# Prestamos por fecha
@require_http_methods(['GET'])
def prestamo_por_fecha(req, fecha=None):
    if fecha:
        prestamos = Prestamo.objects.filter(fecha_comienzo=fecha).all()
        tmp = []
        for pr in prestamos:
            tmp.append(
                {
                    'libro': pr.copia_libro_id.isbn.titulo,
                    'socio': pr.socio_id.nombre_completo,
                    'fecha': pr.fecha_comienzo + timezone.timedelta(7),
                    'estado': pr.estado_string().capitalize()
                }
            )
        return JsonResponse({
            'data': tmp
        })

    else:
        return render(req, 'prestamos/por_fecha.html')


# ABM Devolucion
@require_http_methods(['POST'])
def create_devolucion(req, id_socio, nro_inventario):
    soc = get_object_or_404(Socio, pk=id_socio)
    cop = get_object_or_404(CopiaLibro, pk=nro_inventario)

    try:
        cop.estado = 'd'
        cop.save()

        pr = cop.prestamo_set.filter(copia_libro_id=cop, socio_id=soc, estado='p').get()
        pr.estado = 't'
        pr.fecha_fin = timezone.now().date()
        pr.save()

        msg = "Libro devuelto."

        if pr.fecha_fin - pr.fecha_comienzo > timezone.timedelta(7):
            soc.estado = 'm'
            soc.save()
            msg += " Socio marcado como Moroso."

        return JsonResponse({
            'error': False,
            'msg': msg
        })

    except Exception as e:
        return JsonResponse({
            'error': True,
            'msg': 'Error: {}'.format(e)
        })

biblio/views.py
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.http import require_http_methods
from django.views.generic import View
from django.shortcuts import render, redirect
from biblio.models import Libro, Socio, CopiaLibro


# Login
class LoginController(View):

    @staticmethod
    def get(req):
        return render(req, 'auth/login.html')

    @staticmethod
    def post(req):
        username = req.POST['username']
        passwd = req.POST['password']

        user = authenticate(req, username=username, password=passwd)
        if user is not None:
            login(req, user)
            return redirect('biblio:index')

        else:
            return render(req, 'auth/login.html', {
                'error': 'Usuario y/o contraseña incorrecta!',
                'old': {
                    'username': username
                }
            })


# Logout
@require_http_methods(['GET'])
def my_logout(req):
    logout(req)
    return redirect('biblio:login')


# Index
@require_http_methods(['GET'])
def index(req):
    return render(req, 'index.html', {
        'cant_libros': Libro.objects.count(),
        'cant_copias': CopiaLibro.objects.count(),
        'cant_libros_prestados': Libro.objects.filter(copialibro__estado='p').count(),
        'cant_socios': Socio.objects.count(),
        'cant_socios_morosos': Socio.objects.filter(estado='m').count()
    })

biblio/templates/libros/index.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <button id="btnCreate" class="btn btn-primary">Registrar libro</button>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ISBN</th>
                    <th>Titulo</th>
                    <th>Autor</th>
                    <th>Fecha de ingreso</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for lib in libros %}
                    <tr data-id="{{ lib.id }}" data-isbn="{{ lib.isbn }}">
                        <td>{{ lib.isbn }}</td>
                        <td>{{ lib.titulo }}</td>
                        <td>{{ lib.autor }}</td>
                        <td>{{ lib.fecha_ingreso }}</td>
                        <td>
                            <button class="btn btn-info btn-information" data-id="{{ lib.id }}" data-isbn="{{ lib.isbn }}">Información</button>
                            -
                            <button class="btn btn-info btn-edit" data-id="{{ lib.id }}" data-isbn="{{ lib.isbn }}">Editar</button>
                            -
                            <button class="btn btn-danger btn-delete" data-id="{{ lib.id }}" data-isbn="{{ lib.isbn }}">Eliminar</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="CreateOrEdit" method="POST" action="{% url 'biblio:libros' %}">
                    {% csrf_token %}
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Registrar libro</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="isbn">ISBN</label>
                                    <input class="form-control" type="text" id="isbn" name="isbn">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="code">Código</label>
                                    <input class="form-control" type="text" id="code" name="code">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="date">Fecha</label>
                                    <input class="form-control" type="date" id="date" name="date" disabled>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="title">Titulo</label>
                                    <input class="form-control" type="text" id="title" name="title">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="author">Autor</label>
                                    <input class="form-control" type="text" id="author" name="author">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        <button id="btnAccept" type="submit" class="btn btn-primary">Registrar</button>
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <div class="modal fade" id="myInfoModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Información del libro</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="infoIsbn">ISBN</label>
                                <input class="form-control" type="text" id="infoIsbn" name="infoIsbn" disabled>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="infoCode">Código</label>
                                <input class="form-control" type="text" id="infoCode" name="infoCode" disabled>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="infoDate">Fecha</label>
                                <input class="form-control" type="date" id="infoDate" name="infoDate" disabled>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="infoTitle">Titulo</label>
                                <input class="form-control" type="text" id="infoTitle" name="infoTitle" disabled>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="infoAuthor">Autor</label>
                                <input class="form-control" type="text" id="infoAuthor" name="infoAuthor" disabled>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="text-center">Copias del libro</h3>
                            <table id="table" class="table table-bordered" width="100%">
                            <thead>
                                <tr>
                                    <th>Nro. Inventario</th>
                                    <th>Estado</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <!-- Se incluye el estilo de SweetAlert -->
    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/datatables.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/datatables.min.css' %}">
    <script src="{% static 'js/libros.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
{% endblock %}